import React, { useState } from 'react';
import { 
  Zap, 
  Thermometer, 
  Flame, 
  Gauge, 
  TrendingUp, 
  TrendingDown, 
  Minus, 
  Loader2, 
  AlertCircle, 
  Sparkles
} from 'lucide-react';
import { FORECAST_HORIZONS, getMockForecastData } from '../data/mockForecastData';

/**
 * ForecastPanel Component
 * 
 * Displays forecasted station parameters generated by an ML model.
 * Reusable and decoupled from backend/model logic.
 * 
 * @param {Object} props
 * @param {Object} [props.forecastData] - External forecast payload (matches schema). If null, uses mock data.
 * @param {boolean} [props.loading=false] - When true, displays "Generating forecast..." state.
 * @param {boolean} [props.empty=false] - When true, displays "No forecast available" state.
 * @param {string} [props.selectedHorizon] - Currently selected forecast horizon.
 * @param {Function} [props.onHorizonChange] - Callback when user toggles horizon.
 * @param {string} [props.className] - Additional wrapper CSS classes.
 */
export default function ForecastPanel({
  forecastData: externalData = null,
  loading = false,
  empty = false,
  selectedHorizon: controlledHorizon,
  onHorizonChange,
  className = ''
}) {
  // Internal horizon state if not controlled externally
  const [internalHorizon, setInternalHorizon] = useState('Next 6 Hours');
  const activeHorizon = controlledHorizon || internalHorizon;

  // Selected parameter for the "Predicted vs Current" line chart
  const [selectedParamId, setSelectedParamId] = useState('power_demand');

  // Handle horizon switch
  const handleSelectHorizon = (horizon) => {
    if (onHorizonChange) {
      onHorizonChange(horizon);
    } else {
      setInternalHorizon(horizon);
    }
  };

  // Resolve current active data (prop or mock)
  const currentData = externalData || getMockForecastData(activeHorizon);

  // Status badge styling helper (green = normal/healthy, amber = warning, red = critical)
  const getStatusBadge = (status) => {
    switch (status) {
      case 'critical':
        return {
          label: 'Critical',
          badgeClass: 'bg-rose-50 text-rose-800 border-rose-200',
          dotClass: 'bg-rose-500'
        };
      case 'warning':
        return {
          label: 'Warning',
          badgeClass: 'bg-amber-50 text-amber-800 border-amber-200',
          dotClass: 'bg-amber-500'
        };
      case 'normal':
      default:
        return {
          label: 'Normal',
          badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-200',
          dotClass: 'bg-emerald-500'
        };
    }
  };

  // Trend icon and text styling helper
  const getTrendVisuals = (trend) => {
    switch (trend) {
      case 'Increasing':
        return {
          icon: <TrendingUp className="w-3.5 h-3.5 text-amber-600 shrink-0" />,
          textClass: 'text-amber-700'
        };
      case 'Decreasing':
        return {
          icon: <TrendingDown className="w-3.5 h-3.5 text-blue-600 shrink-0" />,
          textClass: 'text-blue-700'
        };
      case 'Stable':
      default:
        return {
          icon: <Minus className="w-3.5 h-3.5 text-gray-500 shrink-0" />,
          textClass: 'text-gray-600'
        };
    }
  };

  // Parameter icon helper
  const getParameterIcon = (id) => {
    switch (id) {
      case 'power_demand':
        return <Zap className="w-4 h-4 text-blue-600" />;
      case 'temperature':
        return <Thermometer className="w-4 h-4 text-cyan-600" />;
      case 'fuel_consumption':
        return <Flame className="w-4 h-4 text-amber-600" />;
      case 'energy_load':
        return <Gauge className="w-4 h-4 text-indigo-600" />;
      default:
        return <Sparkles className="w-4 h-4 text-blue-600" />;
    }
  };

  // ---------------------------------------------------------------------------
  // 1. LOADING STATE: "Generating forecast..."
  // ---------------------------------------------------------------------------
  if (loading) {
    return (
      <div className={`flex flex-col items-center justify-center p-8 text-center bg-white rounded-xl border border-gray-200 min-h-[360px] space-y-4 ${className}`}>
        <div className="relative flex items-center justify-center">
          <div className="w-12 h-12 rounded-full bg-blue-50 border border-blue-100 flex items-center justify-center">
            <Loader2 className="w-6 h-6 text-blue-600 animate-spin" />
          </div>
        </div>
        <div>
          <h3 className="text-base font-bold text-gray-900 tracking-tight">
            Generating forecast...
          </h3>
          <p className="text-xs text-gray-500 mt-1 max-w-[240px] leading-relaxed">
            Running ML predictive inference on station telemetry streams.
          </p>
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // 2. EMPTY STATE: "No forecast available"
  // ---------------------------------------------------------------------------
  if (empty || !currentData || !currentData.parameters || currentData.parameters.length === 0) {
    return (
      <div className={`flex flex-col items-center justify-center p-8 text-center bg-white rounded-xl border border-gray-200 min-h-[360px] space-y-3 ${className}`}>
        <div className="w-12 h-12 rounded-full bg-gray-50 border border-gray-200 flex items-center justify-center text-gray-400">
          <AlertCircle className="w-6 h-6 stroke-[1.5]" />
        </div>
        <div>
          <h3 className="text-base font-bold text-gray-900 tracking-tight">
            No forecast available
          </h3>
          <p className="text-xs text-gray-500 mt-1 max-w-[240px] leading-relaxed">
            Telemetry stream disconnected or model output has not been generated for this horizon.
          </p>
        </div>
      </div>
    );
  }

  // Active parameter data for line chart
  const activeParam = currentData.parameters.find((p) => p.id === selectedParamId) || currentData.parameters[0];
  const chartPoints = activeParam.chartData || [];

  // Compute SVG chart coordinates
  const svgWidth = 420;
  const svgHeight = 150;
  const padding = { top: 20, right: 25, bottom: 28, left: 45 };
  const graphWidth = svgWidth - padding.left - padding.right;
  const graphHeight = svgHeight - padding.top - padding.bottom;

  // Extract all numeric values to scale Y-axis
  const allValues = chartPoints.flatMap((d) => [
    d.current !== null ? d.current : null,
    d.predicted !== null ? d.predicted : null
  ]).filter((v) => v !== null);

  const rawMin = allValues.length ? Math.min(...allValues) : 0;
  const rawMax = allValues.length ? Math.max(...allValues) : 100;
  const marginRange = (rawMax - rawMin) * 0.15 || 5;
  const yMin = rawMin - marginRange;
  const yMax = rawMax + marginRange;

  const getX = (index) => {
    if (chartPoints.length <= 1) return padding.left + graphWidth / 2;
    return padding.left + (index / (chartPoints.length - 1)) * graphWidth;
  };

  const getY = (val) => {
    if (yMax === yMin) return padding.top + graphHeight / 2;
    return padding.top + graphHeight - ((val - yMin) / (yMax - yMin)) * graphHeight;
  };

  // Build SVG path strings
  // Observed / Current Line
  const currentPoints = chartPoints
    .map((d, i) => (d.current !== null ? { x: getX(i), y: getY(d.current), val: d.current } : null))
    .filter(Boolean);

  const currentPathD = currentPoints.reduce((acc, pt, i) => {
    return i === 0 ? `M ${pt.x} ${pt.y}` : `${acc} L ${pt.x} ${pt.y}`;
  }, '');

  // Predicted Line (All points)
  const predictedPoints = chartPoints
    .map((d, i) => ({ x: getX(i), y: getY(d.predicted), val: d.predicted }));

  const predictedPathD = predictedPoints.reduce((acc, pt, i) => {
    return i === 0 ? `M ${pt.x} ${pt.y}` : `${acc} L ${pt.x} ${pt.y}`;
  }, '');

  return (
    <div className={`bg-white rounded-xl flex flex-col space-y-4 ${className}`}>
      {/* -------------------------------------------------------------------- */}
      {/* HEADER & SUBTITLE                                                    */}
      {/* -------------------------------------------------------------------- */}
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-base font-bold text-gray-900 tracking-tight">
            Forecast
          </h2>
          <p className="text-xs text-gray-500 font-medium mt-0.5">
            Predicted station conditions
          </p>
        </div>

        {/* Small model indicator */}
        <span className="text-[10px] font-mono text-gray-400 bg-gray-50 border border-gray-200 px-2 py-0.5 rounded">
          ML Inferred
        </span>
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* FORECAST HORIZON SELECTOR                                            */}
      {/* -------------------------------------------------------------------- */}
      <div className="flex items-center gap-1.5 p-1 bg-gray-50 border border-gray-200 rounded-lg">
        {FORECAST_HORIZONS.map((horizon) => {
          const isActive = activeHorizon === horizon;
          return (
            <button
              key={horizon}
              type="button"
              onClick={() => handleSelectHorizon(horizon)}
              className={`flex-1 py-1.5 px-2 text-xs font-semibold rounded-md transition-all cursor-pointer text-center ${
                isActive
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100'
              }`}
            >
              {horizon}
            </button>
          );
        })}
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* FORECAST CARDS GRID                                                  */}
      {/* -------------------------------------------------------------------- */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
        {currentData.parameters.map((param) => {
          const isSelected = param.id === activeParam.id;
          const statusVisuals = getStatusBadge(param.status);
          const trendVisuals = getTrendVisuals(param.trend);

          return (
            <div
              key={param.id}
              onClick={() => setSelectedParamId(param.id)}
              className={`p-3.5 rounded-xl border transition-all cursor-pointer flex flex-col justify-between ${
                isSelected
                  ? 'border-blue-500 bg-blue-50/20 shadow-xs ring-1 ring-blue-500/20'
                  : 'border-gray-200 bg-white hover:border-gray-300 hover:bg-gray-50/50 shadow-2xs'
              }`}
            >
              {/* Card Header: Icon, Name & Status */}
              <div className="flex items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2">
                  <div className="p-1 rounded-md bg-gray-50 border border-gray-100 shrink-0">
                    {getParameterIcon(param.id)}
                  </div>
                  <span className="text-xs font-bold text-gray-900 leading-none">
                    {param.name}
                  </span>
                </div>

                {/* Status Dot / Badge */}
                <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-semibold border ${statusVisuals.badgeClass}`}>
                  <span className={`w-1.5 h-1.5 rounded-full ${statusVisuals.dotClass}`}></span>
                  <span>{statusVisuals.label}</span>
                </span>
              </div>

              {/* Card Metrics: Current vs Forecast */}
              <div className="grid grid-cols-2 gap-2 pt-1 border-t border-gray-100">
                <div>
                  <span className="text-[10px] font-medium text-gray-400 uppercase tracking-wider block">
                    Current
                  </span>
                  <span className="font-mono text-xs font-semibold text-gray-700">
                    {param.currentValue} {param.unit}
                  </span>
                </div>

                <div>
                  <span className="text-[10px] font-medium text-blue-600 uppercase tracking-wider block">
                    Forecast
                  </span>
                  <span className="font-mono text-xs font-bold text-gray-900">
                    {param.forecastValue} {param.unit}
                  </span>
                </div>
              </div>

              {/* Trend Indicator */}
              <div className="mt-2.5 pt-2 border-t border-gray-50 flex items-center justify-between text-[11px]">
                <span className="text-gray-400 font-medium">Trend:</span>
                <span className={`font-semibold flex items-center gap-1 ${trendVisuals.textClass}`}>
                  {trendVisuals.icon}
                  <span>{param.trend}</span>
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* LINE CHART: "PREDICTED VS CURRENT"                                   */}
      {/* -------------------------------------------------------------------- */}
      <div className="bg-gray-50/80 border border-gray-200 rounded-xl p-3.5 space-y-2.5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xs font-bold text-gray-900 tracking-tight">
              Predicted vs Current
            </h3>
            <span className="text-[11px] text-gray-500 font-medium">
              {activeParam.name} ({activeParam.unit}) • {activeHorizon}
            </span>
          </div>

          {/* Chart Legend */}
          <div className="flex items-center gap-3 text-[10px] font-medium text-gray-500">
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-0.5 bg-gray-500 rounded"></span>
              Current
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-0.5 bg-blue-600 rounded"></span>
              Predicted
            </span>
          </div>
        </div>

        {/* SVG Responsive Line Chart */}
        <div className="w-full overflow-hidden">
          <svg
            viewBox={`0 0 ${svgWidth} ${svgHeight}`}
            className="w-full h-auto select-none"
          >
            {/* Horizontal Grid lines */}
            {[0, 0.25, 0.5, 0.75, 1].map((ratio, idx) => {
              const y = padding.top + ratio * graphHeight;
              const value = yMax - ratio * (yMax - yMin);
              return (
                <g key={idx}>
                  <line
                    x1={padding.left}
                    y1={y}
                    x2={svgWidth - padding.right}
                    y2={y}
                    stroke="#e2e8f0"
                    strokeWidth="0.75"
                    strokeDasharray="2,2"
                  />
                  <text
                    x={padding.left - 6}
                    y={y + 3}
                    textAnchor="end"
                    className="text-[9px] font-mono fill-gray-400"
                  >
                    {value.toFixed(1)}
                  </text>
                </g>
              );
            })}

            {/* X-axis time tick labels */}
            {chartPoints.map((d, i) => {
              const x = getX(i);
              return (
                <text
                  key={i}
                  x={x}
                  y={svgHeight - 8}
                  textAnchor="middle"
                  className="text-[9px] font-mono fill-gray-400 font-medium"
                >
                  {d.time}
                </text>
              );
            })}

            {/* ML Predicted Line (Blue, dashed for future projection) */}
            <path
              d={predictedPathD}
              fill="none"
              stroke="#2563eb"
              strokeWidth="2"
              strokeDasharray="4,3"
            />

            {/* Current / Observed Line (Solid slate-600) */}
            {currentPathD && (
              <path
                d={currentPathD}
                fill="none"
                stroke="#475569"
                strokeWidth="2"
              />
            )}

            {/* Current Data Points */}
            {currentPoints.map((pt, i) => (
              <circle
                key={`curr-${i}`}
                cx={pt.x}
                cy={pt.y}
                r="3"
                className="fill-white stroke-slate-700"
                strokeWidth="1.5"
              />
            ))}

            {/* Predicted Data Points */}
            {predictedPoints.map((pt, i) => (
              <circle
                key={`pred-${i}`}
                cx={pt.x}
                cy={pt.y}
                r="3"
                className="fill-white stroke-blue-600"
                strokeWidth="1.5"
              />
            ))}
          </svg>
        </div>
      </div>
    </div>
  );
}
