import React, { useState, useRef } from 'react';
import { 
  Zap, 
  Thermometer, 
  Flame, 
  Gauge, 
  TrendingUp, 
  TrendingDown, 
  Minus, 
  Loader2, 
  AlertCircle, 
  Sparkles
} from 'lucide-react';
import { FORECAST_HORIZONS, getMockForecastData } from '../data/mockForecastData';
import ChartTooltip from './ChartTooltip';

/**
 * ForecastPanel Component
 * 
 * Displays forecasted station parameters generated by an ML model.
 * Compact sidebar design with clear PREDICTED indicators, parameter rows,
 * and an interactive trend line chart.
 * 
 * @param {Object} props
 * @param {Object} [props.forecastData] - External forecast payload (matches schema). If null, uses mock data.
 * @param {boolean} [props.loading=false] - When true, displays "Generating forecast..." state.
 * @param {boolean} [props.empty=false] - When true, displays "No forecast available" state.
 * @param {string} [props.selectedHorizon] - Currently selected forecast horizon.
 * @param {Function} [props.onHorizonChange] - Callback when user toggles horizon.
 * @param {string} [props.className] - Additional wrapper CSS classes.
 */
export default function ForecastPanel({
  forecastData: externalData = null,
  loading = false,
  empty = false,
  selectedHorizon: controlledHorizon,
  onHorizonChange,
  className = ''
}) {
  // Internal horizon state if not controlled externally
  const [internalHorizon, setInternalHorizon] = useState('Next 6 Hours');
  const activeHorizon = controlledHorizon || internalHorizon;

  // Selected parameter for the "Predicted vs Current" line chart
  const [selectedParamId, setSelectedParamId] = useState('power_demand');

  // Interactive chart hover state
  const [hoveredIdx, setHoveredIdx] = useState(null);
  const chartContainerRef = useRef(null);

  // Handle horizon switch
  const handleSelectHorizon = (horizon) => {
    if (onHorizonChange) {
      onHorizonChange(horizon);
    } else {
      setInternalHorizon(horizon);
    }
  };

  // Resolve current active data (prop or mock)
  const currentData = externalData || getMockForecastData(activeHorizon);

  // Status badge styling helper
  const getStatusBadge = (status) => {
    switch (status) {
      case 'critical':
        return {
          label: 'Critical',
          badgeClass: 'bg-rose-50 text-rose-800 border-rose-200',
          dotClass: 'bg-rose-500'
        };
      case 'warning':
        return {
          label: 'Warning',
          badgeClass: 'bg-amber-50 text-amber-800 border-amber-200',
          dotClass: 'bg-amber-500'
        };
      case 'normal':
      default:
        return {
          label: 'Normal',
          badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-200',
          dotClass: 'bg-emerald-500'
        };
    }
  };

  // Trend icon and text styling helper
  const getTrendVisuals = (trend) => {
    switch (trend) {
      case 'Increasing':
        return {
          icon: <TrendingUp className="w-3.5 h-3.5 text-amber-600 shrink-0" />,
          textClass: 'text-amber-700'
        };
      case 'Decreasing':
        return {
          icon: <TrendingDown className="w-3.5 h-3.5 text-blue-600 shrink-0" />,
          textClass: 'text-blue-700'
        };
      case 'Stable':
      default:
        return {
          icon: <Minus className="w-3.5 h-3.5 text-gray-500 shrink-0" />,
          textClass: 'text-gray-600'
        };
    }
  };

  // Parameter icon helper
  const getParameterIcon = (id) => {
    switch (id) {
      case 'power_demand':
        return <Zap className="w-3.5 h-3.5 text-blue-600" />;
      case 'temperature':
        return <Thermometer className="w-3.5 h-3.5 text-cyan-600" />;
      case 'fuel_consumption':
        return <Flame className="w-3.5 h-3.5 text-amber-600" />;
      case 'energy_load':
        return <Gauge className="w-3.5 h-3.5 text-indigo-600" />;
      default:
        return <Sparkles className="w-3.5 h-3.5 text-blue-600" />;
    }
  };

  // Loading state
  if (loading) {
    return (
      <div className={`flex flex-col items-center justify-center p-6 text-center bg-gray-50/50 rounded-xl border border-gray-200 min-h-[220px] space-y-3 ${className}`}>
        <div className="w-9 h-9 rounded-full bg-blue-50 border border-blue-100 flex items-center justify-center">
          <Loader2 className="w-5 h-5 text-blue-600 animate-spin" />
        </div>
        <div>
          <h4 className="text-xs font-bold text-gray-900 tracking-tight">
            Generating forecast...
          </h4>
          <p className="text-[11px] text-gray-500 mt-0.5 max-w-[200px] leading-relaxed">
            Running ML predictive inference on station telemetry streams.
          </p>
        </div>
      </div>
    );
  }

  // Empty state
  if (empty || !currentData || !currentData.parameters || currentData.parameters.length === 0) {
    return (
      <div className={`flex flex-col items-center justify-center p-6 text-center bg-gray-50/50 rounded-xl border border-gray-200 min-h-[220px] space-y-2 ${className}`}>
        <AlertCircle className="w-6 h-6 stroke-[1.5] text-gray-400" />
        <h4 className="text-xs font-bold text-gray-900 tracking-tight">
          No forecast available
        </h4>
        <p className="text-[11px] text-gray-500 max-w-[200px] leading-relaxed">
          Predictive inference is unavailable for this horizon.
        </p>
      </div>
    );
  }

  // Active parameter data for line chart
  const activeParam = currentData.parameters.find((p) => p.id === selectedParamId) || currentData.parameters[0];
  const chartPoints = activeParam.chartData || [];

  // Compute SVG chart coordinates for compact sidebar width
  const svgWidth = 320;
  const svgHeight = 110;
  const padding = { top: 12, right: 15, bottom: 22, left: 36 };
  const graphWidth = svgWidth - padding.left - padding.right;
  const graphHeight = svgHeight - padding.top - padding.bottom;

  // Extract all numeric values to scale Y-axis
  const allValues = chartPoints.flatMap((d) => [
    d.current !== null ? d.current : null,
    d.predicted !== null ? d.predicted : null
  ]).filter((v) => v !== null);

  const rawMin = allValues.length ? Math.min(...allValues) : 0;
  const rawMax = allValues.length ? Math.max(...allValues) : 100;
  const marginRange = (rawMax - rawMin) * 0.15 || 5;
  const yMin = rawMin - marginRange;
  const yMax = rawMax + marginRange;

  const getX = (index) => {
    if (chartPoints.length <= 1) return padding.left + graphWidth / 2;
    return padding.left + (index / (chartPoints.length - 1)) * graphWidth;
  };

  const getY = (val) => {
    if (yMax === yMin) return padding.top + graphHeight / 2;
    return padding.top + graphHeight - ((val - yMin) / (yMax - yMin)) * graphHeight;
  };

  // Build SVG path strings
  const currentPoints = chartPoints
    .map((d, i) => (d.current !== null ? { x: getX(i), y: getY(d.current), val: d.current } : null))
    .filter(Boolean);

  const currentPathD = currentPoints.reduce((acc, pt, i) => {
    return i === 0 ? `M ${pt.x} ${pt.y}` : `${acc} L ${pt.x} ${pt.y}`;
  }, '');

  const predictedPoints = chartPoints
    .map((d, i) => ({ x: getX(i), y: getY(d.predicted), val: d.predicted }));

  const predictedPathD = predictedPoints.reduce((acc, pt, i) => {
    return i === 0 ? `M ${pt.x} ${pt.y}` : `${acc} L ${pt.x} ${pt.y}`;
  }, '');

  // Handle chart mouse move for snapping to nearest data point
  const handleChartMouseMove = (e) => {
    if (!chartContainerRef.current || chartPoints.length === 0) return;
    const rect = chartContainerRef.current.getBoundingClientRect();
    const mouseX = e.clientX - rect.left;
    const normX = (mouseX / rect.width) * svgWidth;

    let nearestIdx = 0;
    let minDiff = Infinity;
    chartPoints.forEach((_, i) => {
      const px = getX(i);
      const diff = Math.abs(normX - px);
      if (diff < minDiff) {
        minDiff = diff;
        nearestIdx = i;
      }
    });
    setHoveredIdx(nearestIdx);
  };

  const handleChartMouseLeave = () => {
    setHoveredIdx(null);
  };

  return (
    <div className={`flex flex-col space-y-3.5 ${className}`}>
      {/* -------------------------------------------------------------------- */}
      {/* HEADER & PREDICTED BADGE                                             */}
      {/* -------------------------------------------------------------------- */}
      <div className="flex items-start justify-between gap-2">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-sm font-bold text-gray-900 tracking-tight">
              Forecast
            </h3>
            {/* Small distinct PREDICTED badge */}
            <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-mono font-bold text-indigo-700 bg-indigo-50 border border-indigo-200/90 shadow-2xs tracking-wider">
              <Sparkles className="w-2.5 h-2.5 text-indigo-500" />
              PREDICTED
            </span>
          </div>
          <p className="text-xs text-gray-500 font-medium mt-0.5">
            ML-based predicted station conditions
          </p>
        </div>
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* FORECAST HORIZON SELECTOR                                            */}
      {/* -------------------------------------------------------------------- */}
      <div className="flex items-center gap-1 p-1 bg-gray-100/80 border border-gray-200 rounded-lg">
        {FORECAST_HORIZONS.map((horizon) => {
          const isActive = activeHorizon === horizon;
          return (
            <button
              key={horizon}
              type="button"
              onClick={() => handleSelectHorizon(horizon)}
              className={`flex-1 py-1 px-1.5 text-[11px] font-semibold rounded transition-all cursor-pointer text-center truncate ${
                isActive
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-white/70'
              }`}
            >
              {horizon}
            </button>
          );
        })}
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* COMPACT PARAMETER CARDS / ROWS: Current → Forecast                   */}
      {/* -------------------------------------------------------------------- */}
      <div className="space-y-1.5">
        {currentData.parameters.map((param) => {
          const isSelected = param.id === activeParam.id;
          const statusVisuals = getStatusBadge(param.status);
          const trendVisuals = getTrendVisuals(param.trend);

          return (
            <div
              key={param.id}
              onClick={() => setSelectedParamId(param.id)}
              className={`px-3 py-2 rounded-lg border transition-all cursor-pointer flex items-center justify-between gap-2 ${
                isSelected
                  ? 'border-indigo-400 bg-indigo-50/40 shadow-2xs ring-1 ring-indigo-400/30'
                  : 'border-gray-200 bg-gray-50/60 hover:bg-gray-100/70 hover:border-gray-300'
              }`}
            >
              {/* Left: Icon, Parameter Name, Current Value */}
              <div className="flex items-center gap-2 min-w-0">
                <div className="p-1 rounded bg-white border border-gray-200 shrink-0">
                  {getParameterIcon(param.id)}
                </div>
                <div className="truncate">
                  <div className="text-xs font-semibold text-gray-900 leading-tight truncate">
                    {param.name}
                  </div>
                  <div className="text-[10px] text-gray-400 font-mono mt-0.5">
                    Current: <span className="text-gray-700 font-medium">{param.currentValue} {param.unit}</span>
                  </div>
                </div>
              </div>

              {/* Right: Forecast Value & Trend */}
              <div className="flex items-center gap-2 shrink-0">
                <div className="text-right">
                  <div className="text-[9px] text-indigo-600 uppercase font-bold tracking-wider leading-none">
                    Forecast
                  </div>
                  <div className="text-xs font-bold font-mono text-gray-900 mt-0.5">
                    {param.forecastValue} {param.unit}
                  </div>
                </div>
                <span 
                  className={`inline-flex items-center justify-center w-5 h-5 rounded border ${statusVisuals.badgeClass}`}
                  title={`Trend: ${param.trend} (${param.status})`}
                >
                  {trendVisuals.icon}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* -------------------------------------------------------------------- */}
      {/* COMPACT FORECAST TREND CHART UNDERNEATH METRICS                      */}
      {/* -------------------------------------------------------------------- */}
      <div className="bg-gray-50/90 border border-gray-200 rounded-xl p-3 space-y-2">
        <div className="flex items-center justify-between">
          <div className="truncate">
            <h4 className="text-[11px] font-bold text-gray-900 tracking-tight truncate">
              {activeParam.name} Forecast Trend
            </h4>
            <span className="text-[10px] text-gray-500 font-mono">
              Unit: {activeParam.unit}
            </span>
          </div>

          {/* Chart Legend */}
          <div className="flex items-center gap-2 text-[9px] font-medium text-gray-500 shrink-0">
            <span className="flex items-center gap-1">
              <span className="w-2.5 h-0.5 bg-gray-500 rounded"></span>
              Observed
            </span>
            <span className="flex items-center gap-1 text-indigo-700">
              <span className="w-2.5 h-0.5 bg-indigo-600 rounded"></span>
              Predicted
            </span>
          </div>
        </div>

        {/* Responsive Compact SVG Line Chart with Interactive Hover */}
        <div 
          ref={chartContainerRef}
          className="w-full relative overflow-visible cursor-crosshair"
          onMouseMove={handleChartMouseMove}
          onMouseLeave={handleChartMouseLeave}
        >
          <svg
            viewBox={`0 0 ${svgWidth} ${svgHeight}`}
            className="w-full h-auto select-none overflow-visible"
          >
            {/* Grid lines */}
            {[0, 0.5, 1].map((ratio, idx) => {
              const y = padding.top + ratio * graphHeight;
              const value = yMax - ratio * (yMax - yMin);
              return (
                <g key={idx}>
                  <line
                    x1={padding.left}
                    y1={y}
                    x2={svgWidth - padding.right}
                    y2={y}
                    stroke="#e2e8f0"
                    strokeWidth="0.75"
                    strokeDasharray="2,2"
                  />
                  <text
                    x={padding.left - 4}
                    y={y + 3}
                    textAnchor="end"
                    className="text-[8px] font-mono fill-gray-400"
                  >
                    {value.toFixed(1)}
                  </text>
                </g>
              );
            })}

            {/* X-axis tick labels */}
            {chartPoints.map((d, i) => {
              if (chartPoints.length > 6 && i % 2 !== 0 && i !== chartPoints.length - 1) return null;
              const x = getX(i);
              return (
                <text
                  key={i}
                  x={x}
                  y={svgHeight - 6}
                  textAnchor="middle"
                  className="text-[8px] font-mono fill-gray-400 font-medium"
                >
                  {d.time}
                </text>
              );
            })}

            {/* ML Predicted Line (Indigo, dashed for future projection) */}
            <path
              d={predictedPathD}
              fill="none"
              stroke="#4f46e5"
              strokeWidth="2"
              strokeDasharray="3,2"
            />

            {/* Current / Observed Line (Solid slate-600) */}
            {currentPathD && (
              <path
                d={currentPathD}
                fill="none"
                stroke="#475569"
                strokeWidth="1.75"
              />
            )}

            {/* Current Data Points */}
            {currentPoints.map((pt, i) => (
              <circle
                key={`curr-${i}`}
                cx={pt.x}
                cy={pt.y}
                r={hoveredIdx === i ? "4" : "2.5"}
                className="fill-white stroke-slate-700 transition-all"
                strokeWidth={hoveredIdx === i ? "2" : "1.25"}
              />
            ))}

            {/* Predicted Data Points */}
            {predictedPoints.map((pt, i) => (
              <circle
                key={`pred-${i}`}
                cx={pt.x}
                cy={pt.y}
                r={hoveredIdx === i ? "4" : "2.5"}
                className="fill-white stroke-indigo-600 transition-all"
                strokeWidth={hoveredIdx === i ? "2" : "1.25"}
              />
            ))}

            {/* Hover Guide Line and Active Highlight Circles */}
            {hoveredIdx !== null && chartPoints[hoveredIdx] && (
              <g className="pointer-events-none transition-all duration-150">
                <line
                  x1={getX(hoveredIdx)}
                  y1={padding.top}
                  x2={getX(hoveredIdx)}
                  y2={svgHeight - padding.bottom}
                  stroke="#6366f1"
                  strokeWidth="1.25"
                  strokeDasharray="3,2"
                  opacity="0.8"
                />
                {chartPoints[hoveredIdx].predicted !== null && (
                  <circle
                    cx={getX(hoveredIdx)}
                    cy={getY(chartPoints[hoveredIdx].predicted)}
                    r="5"
                    className="fill-indigo-600 stroke-white"
                    strokeWidth="2"
                  />
                )}
                {chartPoints[hoveredIdx].current !== null && (
                  <circle
                    cx={getX(hoveredIdx)}
                    cy={getY(chartPoints[hoveredIdx].current)}
                    r="5"
                    className="fill-slate-700 stroke-white"
                    strokeWidth="2"
                  />
                )}
              </g>
            )}
          </svg>

          {/* Floating Hover Tooltip */}
          {hoveredIdx !== null && chartPoints[hoveredIdx] && (() => {
            const pt = chartPoints[hoveredIdx];
            const ptX = getX(hoveredIdx);
            const xPercent = (ptX / svgWidth) * 100;
            const items = [];

            if (pt.predicted !== null) {
              items.push({
                label: `Forecast ${activeParam.name}`,
                value: pt.predicted,
                unit: activeParam.unit,
                color: '#4f46e5',
                isForecast: true
              });
            }
            if (pt.current !== null) {
              items.push({
                label: `Observed ${activeParam.name}`,
                value: pt.current,
                unit: activeParam.unit,
                color: '#475569',
                isObserved: true
              });
            }

            return (
              <ChartTooltip
                timestamp={pt.time}
                subtitle="Prediction"
                items={items}
                xPercent={xPercent}
                yPercent={40}
                flipLeft={xPercent > 55}
              />
            );
          })()}
        </div>

        {/* Small distinction footer */}
        <div className="pt-1.5 border-t border-gray-100 flex items-center justify-between text-[9px] font-mono text-gray-400">
          <span>LSTM INFERENCE v2.3</span>
          <span className="text-indigo-600 font-semibold">NOT OFFICIAL NCPOR TELEMETRY</span>
        </div>
      </div>
    </div>
  );
}
